name: Format check on pull request
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  dotnet-format:
    runs-on: windows-2019
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Install dotnet-format
        run: dotnet tool install -g dotnet-format --version 3.3.111304

      - name: Run dotnet format
        id: format
        uses: pamaxie/dotnet-format@v1.0.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          action: "fix"
          only-changed-files: true
          folder: "."
      
      - name: Commit files
        if: steps.format.outputs.has-changes == 'true'
        uses: EndBug/add-and-commit@v4.1.0
        with:
          author_name: Github Actions
          author_email: actions@github.com
          message: Automated dotnet-format update
          ref: ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
